export type Distribution = 'equalSpacing' | 'leading' | 'trailing' | 'center' | 'fill' | 'fillEvenly';
export type Spacing = 'none' | 'extraSmall' | 'small' | 'medium' | 'normal' | 'large' | 'extraLarge';
export type Alignment = 'leading' | 'trailing' | 'center' | 'fill' | 'baseline';
export type Variation = 'positive' | 'negative' | 'strong' | 'subdued';
export type Size = 'small' | 'medium' | 'large' | 'extraLarge';
export type PreferredAlignment = 'left' | 'center' | 'right';
export type Falsy = boolean | undefined | null | 0;
export type Responsive<T> = T | T[];

export type Color =
	| 'white'
	| 'black'
	| 'translucent'
	| 'translucentLight'
	| 'inkLightest'
	| 'inkLighter'
	| 'inkLight'
	| 'ink'
	| 'greyLighter'
	| 'greyLight'
	| 'grey'
	| 'greyDark'
	| 'blueLightest'
	| 'blueLighter'
	| 'blueLight'
	| 'blue'
	| 'blueDark'
	| 'indigoLightest'
	| 'indigoLighter'
	| 'indigoLight'
	| 'indigo'
	| 'indigoDark'
	| 'cyanLightest'
	| 'cyanLighter'
	| 'cyanLight'
	| 'cyan'
	| 'cyanDark'
	| 'greenLightest'
	| 'greenLighter'
	| 'greenLight'
	| 'green'
	| 'greenDark'
	| 'yellowLightest'
	| 'yellowLighter'
	| 'yellowLight'
	| 'yellow'
	| 'yellowDark'
	| 'orangeLightest'
	| 'orangeLighter'
	| 'orangeLight'
	| 'orange'
	| 'orangeDark'
	| 'redLightest'
	| 'redLighter'
	| 'redLight'
	| 'red'
	| 'redDark'
	| 'purpleLightest'
	| 'purpleLighter'
	| 'purpleLight'
	| 'purple'
	| 'purpleDark'
	| 'pinkLightest'
	| 'pinkLighter'
	| 'pinkLight'
	| 'pink'
	| 'pinkDark';
